# Generated by Django 3.0.3 on 2020-02-25 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_achievement_achievement_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
