# Generated by Django 3.0.3 on 2020-02-26 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_codeexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=40, null=True)),
                ('info_content', models.TextField()),
                ('info_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datum publicerat')),
            ],
        ),
    ]
