# Generated by Django 3.0.3 on 2020-02-27 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_indexinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexample',
            name='example_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datum publicerat'),
        ),
    ]
